const facts = [
  "Vào năm 1987 mèo xoán ngôi chó về thú nuôi số một tại Mỹ.",
  "Những con mèo sống theo bầy thường cọ đầu vào nhau để thể hiện chúng không có ý tấn công. Mèo nhỏ thường làm điều này hơn, đặc biệt là khi chúng đang phấn khích.",
  "Mèo mẹ dạy mèo con dùng hộp cát.",
  "Cách bạn đối xử với mèo con vào giai đoạn đầu của cuộc đời sẽ ảnh hưởng lớn đến tính cách của chúng khi trưởng thành.",
  "Trái với niềm tin phổ biến, mèo là loài động vật hướng ngoại. Một con mèo thú cưng sẽ phản hồi và trả lời khi bạn nói, và chúng dường như rất thích đồng hành với con người.",
  "Khi được chăm sóc chu đáo, một con mèo có thể sống lên đến hơn 20 năm nhưng trung bình tuổi thọ của mèo nhà là 14 năm.",
  "Triệt sản một con mèo giúp chúng kéo dài tuổi thọ thêm hai hoặc ba năm.",
  "Mèo, đặc biệt là những con mèo già, có bị ung thư. Căn bệnh này đã được chữa trị thành công rất nhiều lần.",
  "Mèo không thể nếm vị ngọt.",
  "Mèo phải có mỡ trong khẩu phần ăn của chúng vì chúng không thể tự sản xuất mỡ.",
  "Một số cây trồng gây độc cho mèo bao gồm: Cây thường xuân, hoa diên vĩ, tầm gửi, trầu bà và thủy tùng.",
  "Tylenol và sô cô la cũng độc đối với mèo.",
  "Nhiều con mèo không thể tiêu hóa sữa bò. Sữa và sản phẩm từ sữa làm chúng bị tiêu chảy.",
  "Trung bình bữa ăn của mèo tương đương với khoảng năm con chuột.",
  "Mèo có thể bị sán dây từ việc ăn bọ chét. Những con sán kí sinh trong cơ thể mèo suốt đời, hoặc cho đến khi mèo được điều trị. Những con sán sinh sản bằng cách rụng phần phía sau cùng của cơ thể dài ngoằn của chúng. Phần này bò ra khỏi hậu môn của mèo và phân tán hàng trăm trứng sán. Những cái trứng này bị thấp thụ bởi ấu trùng bọ chét, và vòng đời cứ tiếp tục. Con người cũng có thể bị sán dây, nhưng chỉ khi họ ăn những con bọ bị nhiễm sán. Mèo bị sán dây nên được chữa bị bởi bác sĩ thú y.",
  "Mèo có thể bị sán dây từ việc ăn chuột. Nếu mèo của bạn bắt được một con chuột, tốt nhất là nên lấy đi phần thưởng của nó.",
  "Một dạng AIDS tồn tại ở mèo.",
  "Màu của các vùng lông ở mèo Xiên liên quan đến nhiệt độ. Màu lông sẽ đậm hơn ở các vùng lạnh.",
  "Mèo Xiên con sinh ra có màu trắng là vì nhiệt độ của tử cung mèo mẹ trước khi sinh. Nhiệt độ này làm cho màu lông của chúng không bị đậm ở các vùng lông.",
  "Những người dị ứng mèo thực ra là bị dị ứng nước bọt của chúng hoặc lông của chúng. Nếu mèo nhà được tắm điều đặn, người dị ứng sẽ chịu được con mèo tốt hơn.",
  "Nghiên cứu cho thấy dị ứng ở mèo có liên quan đến tuyến mùi hương của chúng. Mèo có tuyến mùi hương ở trên mặt và ở gốc đuôi của chúng. Mèo đực trưởng thành tiết ra nhiều tuyến mùi hương nhất. Nếu chất tiết từ tuyến mùi hương là chất gây dị ứng, những người bị dị ứng tốt nhất nên chịu được những con mèo cái đã được triệt sản.",
  "Mèo không nghĩ rằng chúng là những con người tí hon. Chúng nghĩ rằng chúng ta là những con mèo to lớn. Điều này ảnh hưởng đến hành vi của chúng ở nhiều cách.",
  "Mèo dễ bị mắc các bệnh về răng. Chúng nên được bác sĩ thú y kiểm tra răng hàng năm.",
  "Nhiều người sợ bị nhiễm trùng động vật, nhiễm trùng Toxoplasma, từ mèo. Căn bệnh này có thể làm con người bị bệnh, nghiêm trọng hơn, làm cho trẻ sinh ra bị tật bẩm sinh. Nhiễm trùng Toxoplasma là căn bệnh thông thường, đôi khi lây qua phân mèo. Căn bệnh này thường gặp phải nhất khi ăn thịt bò sống hoặc tái. Phụ nữ mang thai và những người có hệ miễn dịch suy giảm không nên đụng vào hộp cát của mèo. Ngoài những cái đó, không có lý do nào mà những người đó nên tránh mèo.",
  "Tổ tiên của mèo nhà là loài mèo hoang châu Phi, mà vẫn còn tồn tại đến ngày nay.",
  "Vào thời Ai Cập cổ đại, giết mèo là một tội ác và có thể bị tử hình.",
  "Vào thời Ai Cập cổ đại, mèo được ướp xác và xác ướp chuột được đặt cùng với chúng trong mộ của chúng. Ở một thành phố cổ, hơn 300,000 xác ướp mèo đã được tìm thấy.",
  "Vào thời Trung Cổ, trong suốt lễ hội Thánh Join, mèo bị thiêu sống ở quảng trường làng.",
  "Triển lãm mèo được tổ chức đầu tiên vào năm 1871 ở Crystal Palace, London.",
  "Ngày nay có khoảng hơn 100 loại mèo nhà khác nhau.",
  "Như chim, mèo cũng có khả năng về nhà mà sử dụng đồng hồ sinh học của chúng, góc nghiêng mặt trời, và từ trường Trái Đất. Một chú mèo bị đưa đi xa nhà có thể tự tìm đường về nhà. Nhưng nếu chủ của chú mèo chuyển nhà đi xa, chú mèo không thể tìm thấy chủ.",
  "Mèo chôn phân của chúng để che giấu mùi hương khỏi kẻ thù.",
  "Mèo ngủ từ 16 đến 18 giờ mỗi ngày. Khi mèo ngủ, chúng vẫn rất cảnh giác với các tác nhân bên ngoài. Nếu bạn kéo đuôi một chú mèo đang ngủ, nó sẽ phản hồi tương ứng.",
  "Ngoài việc ngửi bằng mũi, mèo cũng có thể ngửi bằng một cơ quan bổ sưng gọi là cơ quan của Jacobson, nằm ở bề mặt trên của miệng.",
  "Chlorine trong nước vòi gây khó chịu cho phần nhạy cảm của mũi mèo. Hãy để nước vòi lắng trong 24 giờ trước khi đưa nó cho mèo.",
  "Abraham Lincoln yêu mèo. Ông ấy có bốn con mèo khi vẫn còn sống trong Nhà Trắng.",
  "Julius Ceasar, Henri II, Charles XI, và Napoleon đều sợ mèo.",
  "Mèo có trung bình 24 cái râu, được sắp xếp thành bốn hàng ngang ở mỗi bên.",
  "Từ 'mèo' trong nhiều ngôn ngữ: tiếng Pháp: chat; tiếng Đức: katze; tiếng Ý: gatto; tiếng Tây Ban Nha/Bồ Đào Nha: gato; tiếng Yiddish: kats; tiếng Malta: qattus; tiếng Thụy Điển/Na Uy: katt; tiếng Hà Lan: kat; tiếng Ai Len: kottur; tiếng Hy Lạp: catta; tiếng Hindu: katas; tiếng Nhật: neko; tiếng Ba Lan: kot; tiếng Ukraina: kotuk; tiếng Hawaii: popoki; tiếng Nga: koshka; tiếng Latin: cattus; tiếng Ai Cập: mau; tiếng Thổ Nhĩ Kỳ: kedi; tiếng Amernia: Gatz; tiếng Trung: mao; tiếng Ả Rập: biss; tiếng Inđô: kucing; tiếng Bulgaria: kotka; tiếng Mã Lay: kucing; tiếng Thái: meo; tiếng Romani: pisica; tiếng Litva: katinas; tiếng Séc: kocka; tiếng Slovak: macka; tiếng Basque: catua; tiếng Estonia: kass; tiếng Phần Lan: kissa; tiếng Swahili: paka; tiếng Việt: mèo.",
  "Thống kê chỉ ra rằng người yêu động vật vài năm gần đây thích mèo hơn chó!",
  "Mèo có thể được dạy để đi bộ với dây vòng cổ, nhưng cần rất nhiều thời gian và công sức để dạy chúng. Mèo càng nhỏ, càng dễ dạy.",
  "Purring not always means happiness. Purring could mean a cat is in terrible pain such as during childbirth. Kitten will purr to their mother to let her know they are getting enough milk while nursing. Purring is a process of inhaling and exhaling, usually performed while the mouth is closed. But don't worry, if your cat is purring while your gently petting her and holding her close to you - that is a happy cat!",
  "The catnip plant contains an oil called hepetalactone which does for cats what marijuana does to some people. Not all cats react to it those that do appear to enter a trancelike state. A positive reaction takes the form of the cat sniffing the catnip, then licking, biting, chewing it, rub & rolling on it repeatedly, purring, meowing & even leaping in the air.",
  "Trong tất cả các loài trong họ hàng mèo, mèo nhà là loài duy nhất có thể giữ đuôi thẳng khi đi. Tất cả các loài mèo hoang giữ đuôi của chúng ngang hoặc nhét đuôi vào giữa chân khi đi.",
  "Một chú mèo vui vẻ giữ đuôi cao và vững.",
  "Gần 10% xương của mèo nằm ở đuôi, và đuôi được dùng để giữ thăng bằng.",
  "Cat families usually play best in even numbers. Cats and kittens should be aquired in pairs whenever possible.",
  "Sô cô la nướng là loại sô cô la độc hại nhất cho mèo của bạn.",
  "You check your cats pulse on the inside of the back thigh, where the leg joins to the body. Normal for cats: 110-170 beats per minute.",
  "Báo đốm là loài mèo to duy nhất không gầm.",
  "Góc nhìn của mèo khoảng 185 độ.",
  "Cats have individual preferences for scratching surfaces and angles. Some are horizontal scratchers while others exercise their claws vertically.",
  "The Maine Coone is the only native American long haired breed.",
  "The Maine Coon is 4 to 5 times larger than the Singapura, the smallest breed of cat.",
  "Tabby cats are thought to get their name from Attab, a district in Baghdad, now the capital of Iraq.",
  "Retractable claws are a physical phenomenon that sets cats apart from the rest of the animal kingdom. In the cat family, only cheetahs cannot retract their claws.",
  "Not every cat gets 'high' from catnip. Whether or not a cat responds to it depends upon a recessive gene: no gene, no joy.",
  "A cat can sprint at about thirty-one miles per hour.",
  "In ancient Egypt, when a family cat died, all family members would shave their eyebrows as a sign of mourning.",
  "Cats have been domesticated for half as long as dogs have been.",
  "A cat's whiskers are thought to be a kind of radar, which helps a cat gauge the space it intends to walk through.",
  "A cat can spend five or more hours a day grooming himself.",
  "All cats have three sets of long hairs that are sensitive to pressure - whiskers, eyebrows,and the hairs between their paw pads.",
  "Both humans and cats have identical regions in the brain responsible for emotion.",
  "Não mèo giống não người nhiều hơn so với chó.",
  "Mèo có nhiều xương hơn con người; con người có 206, và mèo có 230.",
  "Mèo có 30 đốt sống--gấp 5 lần so với người.",
  "Mèo là thú cưng phổ biến nhất Hoa Kỳ: Có hơn 88 triệu thú cưng mèo và 74 triệu thú cưng chó.",
  "Mèo có hơn 20 cơ điều kiểu tai của chúng.",
  "Trong tiếng Anh, một nhóm mèo được gọi là clowder.",
  "Có mèo sống sót sau khi rơi từ tầng 32 trở lên (320 mét) xuống mặt bê tông.",
  "Mèo ngủ 70% thời gian trong cuộc đời của chúng.",
  "Một chú mèo đã là thị trưởng của Talkeetna, Alaska, trong 15 years. Tên chú mèo là Stubbs.",
  "Một chú mèo đã tranh cử chức thị trưởng của Mexico City vào năm 2013.",
  "Ở hổ và mèo vằn, phần giữa của lưỡi được bao phủ bởi các gai nhọn hướng về phía sau, dùng để bẻ và kẹp thịt.",
  'Khi mèo nhăn mặt, chúng thường "ngửi mùi". Chúng có cơ quan mà, cùng với chức năng kiểm soát hơi thở, giúp chúng nếm mùi không khí.',
  "Mèo không thể nếm vị ngọt.",
  "Sở hữu mèo có thể giảm một phần ba tỉ lệ bị đột quy và đau tim.",
  "Wikipedia có đoạn ghi âm tiếng mèu kêu meo meo bởi vì tại sao lại không?",
  "Chú mèo to nhất thế giới dài 48.5 inch. https://www.youtube.com/watch?v=gc5M0aGc_EI",
  "Bằng chứng cho rằng mèo thuần hóa xuất hiện từ năm 3600 TCN, 2,000 năm trước các paharon Ai Cập.",
  "Mèo kêu gừ gừ có thể là một hình thức tự hồi phục, vì nó có thể là dấu hiệu của lo lắng hoặc hài lòng. Tương tự, tần số tiếng gừ gừ của mèo nhà bằng với tần số mà cơ và xương có thể tự hồi phục.",
  "Mèo trưởng thành chỉ kêu meo meo để giao tiếp với người.",
  "Chú mèo giàu nhất thế giới có tài sản 13 tỷ đô sau khi chủ qua đời và để lại tài sản cho nó.",
  "Mèo nhận ra giọng của bạn nhưng giả vờ lạnh lùng không quan tâm (có thể bởi vì chúng lạnh lùng thật).",
  "Mèo thường không thể dung nạp Lactose, nên dừng việc cho chúng sữa đi!",
  "Mèo có thể nhảy lên cao đến sáu lần chiều cao của chúng.",
  "Mèo đóng góp vào sự tuyệt chủng của 33 loài khác nhau.",
  "Mèo có thể uống nước biển để sống sót.",
  "Báo săn giao tiếp bằng kêu gừ gừ và meo meo như mèo nhà, chúng không thể gầm như mèo to khác (v.d. sư tử).",
  "80% mèo cam là đực.",
];

const langName = "vietnamese",
  langISO = "vie",
  langLocale = "vn",
  langLocaleName = "Vietnam";

module.exports = {
  langName,
  langISO,
  langLocale,
  langLocaleName,
  code: `${langISO}-${langLocale}`,
  codeName: `${langName} (${langLocaleName})`,
  facts: facts,
};
  